openapi: 3.0.0
info:
  description: 培训补贴申请项目API
  version: '1.0'
  title: '培训补贴申请项目API'
servers:
  - url: 'http://127.0.0.1:9081'
    description: http请求
paths:
  '/audits':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
    get:
      summary: 查询申请列表
      description: 查询申请列表
      operationId: describeAudits
      parameters:
        - name: applyStatus
          in: query
          description: 申报状态
          required: false
          schema:
            type: string
        - name: applyType
          in: query
          description: 申报类型
          required: false
          schema:
            type: string
        - name: speciality
          in: query
          description: 专业类别
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: 申请名称
          required: false
          schema:
            type: string
        - name: projectName
          in: query
          description: 项目名称
          required: false
          schema:
            type: string
        - name: industryBig
          in: query
          description: 行业大类
          required: false
          schema:
            type: string
        - name: trainFormat
          in: query
          description: 培训方式
          required: false
          schema:
            type: string
        - name: courseFormat
          in: query
          description: 授课方式
          required: false
          schema:
            type: string
        - name: organId
          in: query
          description: 组织ID（企业）
          required: false
          schema:
            type: integer
            format: int64
        - name: organName
          in: query
          description: 组织名称（企业）
          required: false
          schema:
            type: string
        - name: parentOrganId
          in: query
          description: 上级组织ID（区）
          required: false
          schema:
            type: integer
            format: int64
        - name: declareId
          in: query
          description: 窗口期ID
          required: false
          schema:
            type: integer
            format: int64
        - name: pageNo
          in: query
          description: 页码
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          description: 每页记录数
          required: false
          schema:
            type: integer
            format: int32
            minimum: 10
            default: 20
        - name: queryType
          in: query
          description: 查询类型，审核audit,项目project,花名册roster
          required: false
          schema:
            type: string
        - name: spotCheck
          in: query
          description: 是否被抽查过
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Audits'
    post:
      summary: 新建申请
      description: 新建申请
      operationId: createAudit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditBrief'
      responses:
        201:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditCreated'
  '/audits/{id}':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: 申请ID
        required: true
        schema:
          type: integer
          format: int64
    get:
      operationId: describeAudit
      summary: 查询指定ID的申请记录
      description: 查询指定ID的申请记录
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditBrief'
    delete:
      operationId: deleteAudit
      summary: 删除指定ID的申请记录
      description: 删除指定ID的申请记录
      responses:
        200:
          description: no content
  '/audits/{id}/apply':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: 申请ID
        required: true
        schema:
          type: integer
          format: int64
    post:
      operationId: applyAudit
      summary: 提报申请
      description: 提报申请
      responses:
        200:
          description: no content
  '/audits/{id}/member':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: 申请ID
        required: true
        schema:
          type: integer
          format: int64
    get:
      operationId: describeMemberInfo
      description: 查询成员信息
      summary: 查询成员信息
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditMember'
    post:
      operationId: saveMemberInfo
      description: 设置成员信息
      summary: 设置成员信息
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditMember'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditCreated'
  '/audits/{id}/course':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: 申请ID
        required: true
        schema:
          type: integer
          format: int64
    get:
      operationId: describeCourseInfo
      description: 查询课程信息
      summary: 查询课程信息
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditCourse'
    post:
      operationId: saveCourseInfo
      description: 设置课程信息
      summary: 设置课程信息
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditCourse'
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditCreated'
  /audits/{id}/protoco':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: 申请ID
        required: true
        schema:
          type: integer
          format: int64
    get:
      operationId: showProtocoImg
      description: 查看培训协议图片
      summary: 查看培训协议图片
      responses:
        200:
          description: ok
  '/audits/{auditId}/files/{id}':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
      - name: auditId
        in: path
        description: 申请ID
        required: true
        schema:
          type: integer
          format: int64
      - name: id
        in: path
        description: 文件ID
        required: true
        schema:
          type: string
    delete:
      description: 删除附件
      summary: 删除附件
      operationId: deleteAuditFile
      responses:
        204:
          description: no content
  '/declare':
    parameters:
      - name: access-token
        in: header
        description: 用户认证信息
        required: true
        schema:
          type: string
      - name: current-role
        in: header
        description: 用户当前角色
        required: true
        schema:
          type: string
    get:
      operationId: describeCurrDeclare
      description: 查询当前窗口期
      summary: 查询当前窗口期
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Declare'
components:
  schemas:
    Audits:
      properties:
        page:
          $ref: '#/components/schemas/Page'
        list:
          type: array
          items:
            $ref: '#/components/schemas/AuditBrief'
    AuditBrief:
      properties:
        id:
          type: integer
          format: int64
          description: id
        title:
          type: string
          description: 申报标题
        creatorId:
          type: integer
          format: int64
          description: 申报人ID
          readOnly: true
        projectName:
          type: string
          description: 项目名称
        applyType:
          type: string
          description: 申请类型
        speciality:
          type: string
          description: 专业类别
        industryBig:
          type: string
          description: 行业大类
        industrySmall:
          type: string
          description: 行业小类
        traineeNumber:
          type: integer
          format: int32
          description: 培训人数
        courseAim:
          type: string
          description: 课程定位
        applyMoney:
          type: number
          description: 申请补贴金额
        projectTotalPeriod:
          type: integer
          format: int64
          description: 项目总学时
        trainFormat:
          type: string
          description: 培训方式
        courseFormat:
          type: string
          description: 授课方式
        applyTime:
          type: string
          format: 'date-time'
          description: 申报时间
          readOnly: true
        applyStatus:
          type: string
          description: 申报状态
          readOnly: true
        organId:
          type: integer
          format: int64
          description: 组织ID
          readOnly: true
        organName:
          type: string
          description: 组织名称
          readOnly: true
        parentOrganId:
          type: integer
          format: int64
          description: 上级组织ID
          readOnly: true
        parentOrganName:
          type: string
          description: 上级组织名称
          readOnly: true
        declareId:
          type: integer
          format: int64
          description: 申报窗口ID
        declareName:
          type: string
          description: 申报窗口名称
        spotCheck:
          type: integer
          format: int32
          description: 是否被抽查过
    Page:
      properties:
        pageNo:
          type: integer
        pageSize:
          type: integer
        total:
          type: integer
          readOnly: true
        pageCount:
          type: integer
          readOnly: true
    AuditCreated:
      properties:
        id:
          type: integer
          format: int64
          description: 申请记录ID
    Declare:
      properties:
        id:
          type: integer
          format: int64
          description: ID
        startTime:
          type: string
          format: 'date-time'
          description: 开始时间
        endTime:
          type: string
          format: 'date-time'
          description: 结束时间
        active:
          type: boolean
          description: 是否激活
        applyWindow:
          type: boolean
          description: 是否是可以申请的窗口值
        userStatus:
          type: boolean
          description: 当前用户是否可以申报
        userReason:
          type: string
          description: 用户原因
    AuditMember:
      properties:
        member:
          type: string
          description: 成员信息
    AuditCourse:
      properties:
        course:
          type: string
          description: 课程信息